### ISSUE TITLE
Status of project?

### ISSUE THREAD

**Issue by jlippold** [brianpeiris/switchmate#19] opened 2019-06-26 11:48 UTC
Hey Brian,

I tried to use this project a while ago and maybe it was right in the midst of firmware changes, so I couldn't get anything working reliably. If I have the latest iOS app, and the newest firmware, does your library work against it? Are there any limitations?

I know I could try it and see for myself, but I'm hoping you don't mind filling me in

Thanks a bunch

**Comment by brianpeiris** [comment] 2019-06-26 17:25
It's been a while since I've used it myself, and I don't use apple devices, so I'd encourage you to try it yourself and report back if you run into issues! I'm not sure what limitations you had in mind, but I can't think of any.

**Comment by Thomasbomb** [comment] 2019-12-06 03:52
has anyone successfully used this with the switchmates? I am considering buying some but I want to confirm I can control via raspberry pi first

**Comment by jlippold** [comment] 2019-12-08 21:41
@Thomasbomb I found it to be unreliable. I purchased a bunch and regret it. If anyone wants to buy them from me, hit me up lol

**Comment by lavahot** [comment] 2019-12-11 06:54
Yeah @jlippold, I'll bite. Are they brights?

**Comment by jlippold** [comment] 2019-12-11 13:08
@lavahot I have 10 [rocker switch models](https://www.amazon.com/Switchmate-Wire-Free-Activated-Assistant-Controlled/dp/B07K1GFYDF/ref=pd_sbs_60_img_2/133-2386734-4904120?_encoding=UTF8&pd_rd_i=B07K1JJSGR&pd_rd_r=10fdcb5b-cb3f-408c-8907-5ace35589345&pd_rd_w=nwTqc&pd_rd_wg=vyghb&pf_rd_p=5cfcfe89-300f-47d2-b1ad-a4e27203a02a&pf_rd_r=8H7QYS1F1KS306E5MKD5&refRID=8H7QYS1F1KS306E5MKD5&th=1)

**Comment by lavahot** [comment] 2019-12-11 23:14
Oh, was looking for toggle. Thanks anyway, @jlippold

**Comment by brianpeiris** [comment] 2019-12-11 23:31
@jlippold When reliability issues did you run into with the script? What type of computer were you running the script on, a Raspberry PI? Sorry to hear it didn't work out for you, but it would be helpful to share more details about the problems that you ran into. Perhaps the script can be improved.

**Comment by jlippold** [comment] 2019-12-12 20:19
I was running a rPi3, so maybe it was the bluetooth range? I'm not 100% sure. I had it wired it up to a web UI and alexa, and I found it took a while to toggle, which wasn't ideal but bearable. The bigger problem was that they sporadically stopped working. 

One day, I'll try again since I have 10 of these things collecting dust, lol. When I do, i'll get better debug logs

**Comment by brianpeiris** [comment] 2019-12-12 22:51
Thanks. If you think bluetooth range was the main issue, I'd suggest trying an external bluetooth adapter connected to the PI with a short USB extension cable. I've seen range issues in the past as well. There might be ways to have the script boost the bluetooth power, but there still might be limits especially if you've got walls in the way.
Perhaps you could do a simple reliability test by keeping the switches in short range over the course of a day and switch them on/off periodically.

**Comment by brianpeiris** [comment] 2020-03-22 00:22
I finally got around to testing the script with my devices. I can confirm that it still works with the latest firmware updates from switchmate on both the original and the slim models. 
I am running into inconsistencies with status checks, but the switch commands seem to be more reliable. I'm not sure if there's much I can do on that front. My guess is the underlying bluepy library is buggy, but it hasn't been updated in over a year. I'm open to suggestions if people have specific ideas. For now I will close this issue, but feel free to open new ones.

**Closed as completed by brianpeiris** 2020-03-22 00:22 UTC
